### ISSUE TITLE
Add a .gitignore 

### ISSUE THREAD

**Issue by frogmasta** [AashishSubramanian26/CS225-Final-Project#21]
Please add a .gitignore to ignore .vscode 🙂

**Comment by frogmasta** [comment]
Would like to follow up

**Comment by AashishSubramanian26** [comment]
Hello

**Comment by AashishSubramanian26** [comment]
On vacation, 

Please contact Ved Eti

**Comment by frogmasta** [comment]
> On vacation,
> 
> Please contact Ved Eti

Could you kindly assign him to this issue? Thanks!

**Comment by AashishSubramanian26** [comment]
alright, will do sir!
